# Generated by Django 4.2.1 on 2023-05-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('fecha_fundacion', models.DateField()),
                ('categoria_juego', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('lugar_de_nacimiento', models.CharField(max_length=256)),
                ('fecha_de_nacimiento', models.DateField()),
                ('trayectoria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('numero_camiseta', models.IntegerField()),
                ('lugar_de_nacimiento', models.CharField(max_length=256)),
                ('fecha_de_nacimiento', models.DateField()),
                ('esta_habilitado', models.BooleanField(default=True)),
            ],
        ),
    ]
