# Generated by Django 4.2.1 on 2023-05-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenadores',
            name='entrena',
            field=models.CharField(default=None, max_length=265),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='juega_para',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
