# Generated by Django 4.2.1 on 2023-05-23 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Basquet1', '0002_clubes_creador_entrenadores_creador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clubes'),
        ),
        migrations.AddField(
            model_name='entrenadores',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='entrenadores'),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores'),
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('fecha_creacion', models.DateField(null=True)),
                ('categoria', models.CharField(max_length=256)),
                ('cuerpo', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos')),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
