# Generated by Django 4.2.1 on 2023-05-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0002_entrenadores_entrena_jugadores_juega_para'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenadores',
            name='entrena',
            field=models.CharField(max_length=265, null=True),
        ),
    ]
