# Generated by Django 4.2.1 on 2023-05-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0003_clubes_imagen_entrenadores_imagen_jugadores_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubes',
            old_name='imagen',
            new_name='Imagen',
        ),
        migrations.RenameField(
            model_name='entrenadores',
            old_name='imagen',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='jugadores',
            old_name='imagen',
            new_name='picture',
        ),
    ]
