# Generated by Django 4.2.1 on 2023-05-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0003_alter_entrenadores_entrena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenadores',
            name='entrena',
            field=models.CharField(default='No se encuentra entrenando', max_length=265),
        ),
    ]
