# Generated by Django 4.2.1 on 2023-05-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0003_clubes_imagen_entrenadores_imagen_jugadores_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='imagen',
            new_name='descriptivo',
        ),
        migrations.AlterField(
            model_name='articulos',
            name='titulo',
            field=models.CharField(max_length=257),
        ),
    ]
