# Generated by Django 4.2.1 on 2023-05-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0004_rename_imagen_clubes_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='imagen',
            new_name='descriptivo',
        ),
        migrations.RenameField(
            model_name='jugadores',
            old_name='picture',
            new_name='picturep',
        ),
    ]
