# Generated by Django 4.2.1 on 2023-05-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0006_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='apellido',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='biografia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='about_me'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='lugar_de_nacimiento',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='nombre',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
