# Generated by Django 4.2.1 on 2023-05-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0007_aboutme_apellido_aboutme_biografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='fecha_creacion',
            field=models.DateField(),
        ),
    ]
