# Generated by Django 4.2.1 on 2023-05-27 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0008_alter_articulos_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadores',
            name='numero_camiseta',
        ),
    ]
