# Generated by Django 4.2.1 on 2023-05-28 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0009_remove_jugadores_numero_camiseta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='creador',
        ),
    ]
