# Generated by Django 4.2.1 on 2023-05-28 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0010_remove_articulos_creador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='articulos',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
