# Generated by Django 4.2.1 on 2023-05-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0012_remove_aboutme_imagen_remove_articulos_descriptivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
