# Generated by Django 4.2.1 on 2023-05-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0013_articulos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='club',
            field=models.CharField(default='Agente Libre', max_length=256),
        ),
    ]
