# Generated by Django 4.2.1 on 2023-05-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0014_jugadores_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='numero_camista',
            field=models.IntegerField(default=0),
        ),
    ]
