# Generated by Django 4.2.1 on 2023-05-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0015_jugadores_numero_camista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugadores',
            old_name='numero_camista',
            new_name='numero_camiseta',
        ),
    ]
