# Generated by Django 4.2.1 on 2023-05-29 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0020_articulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulo',
        ),
    ]
