# Generated by Django 4.2.1 on 2023-05-29 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0021_delete_articulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
