# Generated by Django 4.2.1 on 2023-05-29 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0022_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('subtitulo', models.CharField(max_length=250)),
                ('cuerpo', models.TextField()),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
