# Generated by Django 4.2.1 on 2023-05-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0023_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.CharField(default='Anónimo', max_length=256),
        ),
    ]
