# Generated by Django 4.2.1 on 2023-05-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basquet1', '0025_articulo_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubes',
            name='creador1',
            field=models.CharField(default='Aquí va el nombre de usuario', max_length=256),
        ),
        migrations.AddField(
            model_name='entrenadores',
            name='creador1',
            field=models.CharField(default='Aquí va el nombre de usuario', max_length=256),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='creador1',
            field=models.CharField(default='Aquí va el nombre de usuario', max_length=256),
        ),
    ]
